-- Data types in Postgre SQL
-- 1. int
-- 2. smallint
-- 3. bigint
-- 4. char
-- 5. varchar
-- 6. text
-- 7. boolean
-- 8. null
-- 9. decimal/numeric (int, int)
-- 10. real
-- 11. double precision
CREATE TABLE IF NOT EXISTS students (
	id BIGINT,
	name TEXT,
	is_bonafide BOOLEAN,
	fee DECIMAL(8, 2)
);

INSERT INTO
	students (id, name, is_bonafide, fee)
VALUES
	(1, 'Ali', TRUE, 2345.23),
	(2, 'Ahmad', TRUE, 123456.78),
	(
		3,
		'There was once a time when there was a Lodhi Sultanate in Delhi, then Babar came from Afghanistan.',
		FALSE,
		123456.7
	);

INSERT INTO
	students (name)
VALUES
	('M. Saad Lodhi'),
	('Yar Muhammad Uwaim'),
	('Fateh Ali'),
	('Ammar Khalid');

SELECT
	id,
	name,
	is_bonafide,
	fee
FROM
	students;

DROP TABLE students;

-- task (create a table named schools)
CREATE TABLE IF NOT EXISTS schools (
	id BIGINT,
	name VARCHAR(20),
	is_liscenced BOOLEAN,
	fee DECIMAL(7, 2),
	biography TEXT
);

INSERT INTO
	schools (id, name, is_liscenced, fee, biography)
VALUES
	(
		1,
		'SPRING School ',
		TRUE,
		31242.32,
		'This school was hfkjhfkjabfjahfkjahfkjsahfkjahfkjahfjahfkjhakjfhsdakjfhasjkfh'
	);

SELECT
	*
FROM
	schools;

DROP TABLE schools;

-- Demonstration of serial
CREATE TABLE products (
	id BIGINT,
	name VARCHAR(200),
	description TEXT,
	is_available BOOLEAN
);

INSERT INTO
	products (id, name, description, is_available)
VALUES
	(
		1,
		'Dell Latitude 5540',
		'i7-13th gen intel cpu, 16 gb ddr4 ram, 512 gb nvme ssd',
		TRUE
	),
	(
		2,
		'ASUS 5th gen laptop',
		'A crappy laptop, you should not buy it. We are finishing the stock',
		FALSE
	);

SELECT
	*
FROM
	products;

DROP TABLE products;

CREATE TABLE products (
	id serial,
	name VARCHAR(200),
	description TEXT,
	is_available BOOLEAN
);

INSERT INTO
	products (name, description, is_available)
VALUES
	(
		'Dell Latitude 5540',
		'i7-13th gen intel cpu, 16 gb ddr4 ram, 512 gb nvme ssd',
		TRUE
	),
	(
		'ASUS 5th gen laptop',
		'A crappy laptop, you should not buy it. We are finishing the stock',
		FALSE
	);

SELECT
	*
FROM
	products;

DROP TABLE products;

-- Lets recreate it.
CREATE TABLE products (
	id serial,
	name VARCHAR(200),
	description TEXT,
	is_available BOOLEAN
);

INSERT INTO
	products (id, name, description, is_available)
VALUES
	(
		1,
		'Dell Latitude 5540',
		'Recommended by Yar Muhammad Uwaim. You should buy it without any questions.',
		TRUE
	);

SELECT
	*
FROM
	products;

INSERT INTO
	products (name, description, is_available)
VALUES
	(
		'Dell Latitude 5540',
		'Recommended by Yar Muhammad Uwaim. You should buy it without any questions.',
		TRUE
	);

SELECT
	*
FROM
	products;

DROP TABLE products;

-- What's the solution?
-- 1. Don't give manual input for the serial.
-- 2. unique constraint
-- 3. generated by default as identity
CREATE TABLE products (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(200),
	description TEXT
);

INSERT INTO
	products (id, name, description)
VALUES
	(
		1,
		'Dell Latitude 5540',
		'Recommended by Yar Muhammad Uwaim. You should buy it without any questions.'
	);

INSERT INTO
	products (name, description)
VALUES
	(
		'Dell Latitude 5540',
		'Recommended by Yar Muhammad Uwaim. You should buy it without any questions.'
	);

DROP TABLE products;

CREATE TABLE products (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(200),
	description TEXT
);

INSERT INTO
	products (name, description)
VALUES
	(
		'Dell Latitude 5540',
		'Recommended by Yar Muhammad Uwaim. You should buy it without any questions.'
	);

SELECT
	*
FROM
	products;

DROP TABLE products;

CREATE TABLE employees (id serial, name VARCHAR(20), salary DECIMAL(4, 1));

INSERT INTO
	employees (id, name, salary)
VALUES
	(1, 'Yar Muhamamd Uwaim ', 223.3);

SELECT
	*
FROM
	employees
DROP TABLE employees
CREATE TABLE employees (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(20),
	salary_stat TEXT
)
INSERT INTO
	employees (name, salary_stat)
VALUES
	(
		'Muhammad Saad Lodhi ',
		'The employee has got promotion in the lsat week of the year adn  his current salary is 2090'
	);

SELECT
	*
FROM
	employees;

CREATE VIEW names_view AS
SELECT
	name
FROM
	employees;

SELECT
	*
FROM
	names_view;

CREATE VIEW names_view_2 AS
SELECT
	name
FROM
	employees
WHERE
	id < 5;

SELECT
	*
FROM
	names_view_2;

CREATE OR REPLACE PROCEDURE raise_notice (notice_value TEXT) language plpgsql AS $$
BEGIN 
RAISE NOTICE '%', notice_value;
END;
$$;

CALL raise_notice ('Hello, this is Yar Muhammad Uwaim.');

CREATE OR REPLACE PROCEDURE calculate_sum (a INT, b INT, OUT res INT) language plpgsql AS $$
begin
	res := a + b;
end;
$$;

CALL calculate_sum (1, 2, NULL);

CREATE OR REPLACE PROCEDURE show_first_student (OUT res record) language plpgsql AS $$ 
begin 
	select * into res from students order by marks desc limit 1;
end;
$$;

CREATE EXTENSION if NOT EXISTS citext;

-- Relation student already exists, so dropping it first.
DROP TABLE students;

-- Now recreating students table with the columns of my choice
CREATE TABLE students (
	id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	email citext NOT NULL UNIQUE,
	marks INT NOT NULL
);

-- Some values to be inserted into students table
INSERT INTO
	students (name, email, marks)
VALUES
	('Ali', 'aliraza@gmail.com', 29),
	('Ahmad', 'ahmadalikhan@gmail.com', 89),
	('Ghaffar', 'ghaffar@gmail.com', 78),
	('Lodhi', 'saadlodhi@gmail.com', 98);

-- Calling the procedure
CALL show_first_student (NULL);

-- Creating a procedure for adding a student in the students table.
CREATE OR REPLACE PROCEDURE add_student (name VARCHAR(200), email citext, marks INT) language plpgsql AS $$
BEGIN 
	INSERT INTO students (name, email, marks) VALUES (name, email, marks);
END;
$$;

CALL add_student ('Yar Muhammad', 'yarmuhammadawaim@gmail.com', 100);

CALL show_first_student (NULL);

CALL add_student (
	'Abdullah Saleem',
	'abdullahsaleem@gmail.com',
	200
);

CALL show_first_student (NULL);

CALL add_student (
	'Yar Muhammad Uwaim',
	'yarmuhammaduwaim@gmail.com',
	900
);

CALL show_first_student (NULL);

CALL add_student (
	'Yar Muhammad Uwaim Khan',
	'yarmuhammaduwaimkhan@gmail.com',
	1000
);

CALL show_first_student (NULL);

CREATE OR REPLACE PROCEDURE create_names_view (table__name TEXT, column__name TEXT) LANGUAGE plpgsql AS $$
BEGIN
	EXECUTE format('DROP VIEW names_view; CREATE VIEW names_view as SELECT %s from %s;', column__name, table__name);
END;
$$;

CALL create_names_view ('students', 'name');

SELECT
	*
FROM
	names_view;

SELECT
	*
FROM
	students;

CALL add_student ('Muarra Naseeb', 'muarra.naseeb@gmail.com', 1987);

CALL show_first_student (NULL);

SELECT
	*
FROM
	names_view;

